### PR TITLE
swift 5.1 and Xcode 11 fixes

### PR DESCRIPTION
**Pull request by theromis**

### CODE REVIEW

**Review by thom-bahm — COMMENTED** [review]
yea this is what I was boutta do, good job, this should be approved

**Comment by theromis** [comment]
still one warning: `'statusBarFrame' was deprecated in iOS 13.0: Use the statusBarManager property of the window scene instead.`

for `let statusBarHeight = UIApplication.shared.statusBarFrame.height`
any idea how to fix it?

**Comment by theromis** [comment]
@QuantumThom extra question, is it possible to handle click outside of the menu to toggle it? Bonus question: will be perfect if I can add ability to slide menu back by holding it.

**Comment by theromis** [comment]
did a "dismissal trick" by putting
```
ZStack {
        GeometryReader { _ in
            EmptyView()
        }
        .background(Color.gray.opacity(0.3))
        .opacity(show ? 1.0 : 0.0)
        .animation(Animation.easeIn.delay(0.25))
        .onTapGesture {
            self.show = false
        }

```
under `MenuView`

**Comment by michaelmorehead** [comment]
for the statusBarHeight issue: 'statusBarFrame' was deprecated in iOS 13.0:
Use the statusBarManager property of the window scene instead.

// let statusBarHeight = UIApplication.shared.statusBarFrame.height

let window = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
let statusBarHeight = window?.windowScene?.statusBarManager?.statusBarFrame.height ?? 0

**Comment by theromis** [comment]
@michaelmorehead thank you, used your snippet as extra commit.
Hopefully they will merge finally my PR

**Comment by mythxn** [comment]
@theromis Thanks for the update! Great work :)

**Pull request merged**
